function files = generate_table6_outputs(table6Results,resultsDir,timestamp)
%GENERATE_TABLE6_OUTPUTS Save CSV, MAT, and LaTeX summaries for Table 6.

if nargin < 2 || strlength(string(resultsDir)) == 0
    srcDir = fileparts(mfilename('fullpath'));
    projectRoot = fileparts(srcDir);
    resultsDir = fullfile(projectRoot,'results');
end
if nargin < 3 || strlength(string(timestamp)) == 0
    timestamp = string(datetime('now','Format','yyyy-MM-dd_HH-mm-ss'));
end
if ~isfolder(resultsDir)
    mkdir(resultsDir);
end

completed = ~cellfun(@isempty,table6Results);
results = table6Results(completed);
if isempty(results)
    error('No completed Table 6 results were supplied.');
end

numResults = numel(results);
Instance = strings(numResults,1);
NumVariables = zeros(numResults,1);
NumClauses = zeros(numResults,1);
OptimalValue = NaN(numResults,1);
ILPStatus = strings(numResults,1);
LPBound = NaN(numResults,1);
LPStatus = strings(numResults,1);
OriginalSDPBound = NaN(numResults,1);
OriginalSDPOrder = zeros(numResults,1);
OriginalSDPTime = NaN(numResults,1);
OriginalSDPStatus = strings(numResults,1);
OriginalSDPHistoricalStatus = strings(numResults,1);
ReducedSDPBound = NaN(numResults,1);
ReducedSDPOrder = zeros(numResults,1);
ReducedSDPTime = NaN(numResults,1);
ReducedSDPStatus = strings(numResults,1);
AffineFRTime = NaN(numResults,1);

for i = 1:numResults
    result = results{i};
    Instance(i) = string(result.info.name);
    NumVariables(i) = result.info.n;
    NumClauses(i) = result.info.m;
    OriginalSDPOrder(i) = result.info.n + 1;
    ReducedSDPOrder(i) = result.affineFRA.r;
    AffineFRTime(i) = result.affineFRA.total_time;

    ILPStatus(i) = get_status(result,'ILP');
    if ILPStatus(i) == "INFEASIBLE"
        OptimalValue(i) = Inf;
    else
        OptimalValue(i) = get_value(result,'ILP','objval');
    end

    LPStatus(i) = get_status(result,'LP');
    LPBound(i) = get_value(result,'LP','objval');

    OriginalSDPStatus(i) = get_status(result,'SDP');
    OriginalSDPBound(i) = get_value(result,'SDP','objval');
    OriginalSDPTime(i) = get_value(result,'SDP','runtime');
    if isfield(result,'SDP') && isstruct(result.SDP) && ...
            isfield(result.SDP,'historicalStatus')
        OriginalSDPHistoricalStatus(i) = ...
            string(result.SDP.historicalStatus);
    end

    ReducedSDPStatus(i) = get_status(result,'SDPFR');
    ReducedSDPBound(i) = get_value(result,'SDPFR','objval');
    ReducedSDPTime(i) = get_value(result,'SDPFR','runtime');
end

table6Summary = table(Instance,NumVariables,NumClauses, ...
    OptimalValue,ILPStatus,LPBound,LPStatus, ...
    OriginalSDPBound,OriginalSDPOrder,OriginalSDPTime, ...
    OriginalSDPStatus,OriginalSDPHistoricalStatus, ...
    ReducedSDPBound,ReducedSDPOrder,ReducedSDPTime, ...
    ReducedSDPStatus,AffineFRTime);

prefix = "table6_" + string(timestamp);
files.csvFile = fullfile(resultsDir,prefix + ".csv");
files.matFile = fullfile(resultsDir,prefix + "_summary.mat");
files.latexFile = fullfile(resultsDir,prefix + ".tex");

writetable(table6Summary,files.csvFile);
save(files.matFile,'table6Summary','-v7');
write_latex_table(files.latexFile,table6Summary);

end

function status = get_status(result,fieldName)
status = "";
if isfield(result,fieldName)
    output = result.(fieldName);
    if isstruct(output) && isfield(output,'status')
        status = string(output.status);
    end
end
end

function value = get_value(result,fieldName,valueName)
value = NaN;
if isfield(result,fieldName)
    output = result.(fieldName);
    if isstruct(output) && isfield(output,valueName) && ...
            ~isempty(output.(valueName))
        value = double(output.(valueName));
    end
end
end

function write_latex_table(filename,summary)
fid = fopen(filename,'w');
if fid < 0
    error('Unable to open LaTeX output file: %s',filename);
end
fileCleanup = onCleanup(@() fclose(fid));
rowEnd = '\\';

fprintf(fid,'%s\n','% Generated by generate_table6_outputs.m.');
fprintf(fid,'%s\n','\begin{table}[htbp]');
fprintf(fid,'%s\n','\scriptsize');
fprintf(fid,'%s\n','\centering');
fprintf(fid,'%s\n','\resizebox{\textwidth}{!}{%');
fprintf(fid,'%s\n','\begin{tabular}{lc|c|ccc|ccc} \hline');
fprintf(fid,'%s\n',['\multirow{2}{*}{Instance} & ', ...
    '\multirow{2}{*}{Optimal} & \multirow{2}{*}{LP bound} & ', ...
    '\multicolumn{3}{c|}{Original SDP} & ', ...
    '\multicolumn{3}{c}{Affine FR} \\']);
fprintf(fid,'%s\n',['& & & SDP bound & Matrix Order & Time & ', ...
    'SDP bound & Matrix Order & Time \\ \hline']);

for i = 1:height(summary)
    optimum = format_optimum( ...
        summary.OptimalValue(i),summary.ILPStatus(i));
    lpBound = format_number(summary.LPBound(i));
    originalBound = format_bound(summary.OriginalSDPBound(i), ...
        summary.OriginalSDPStatus(i),summary.OptimalValue(i));
    originalTime = format_time(summary.OriginalSDPTime(i), ...
        summary.OriginalSDPStatus(i));
    reducedBound = format_bound(summary.ReducedSDPBound(i), ...
        summary.ReducedSDPStatus(i),summary.OptimalValue(i));
    reducedTime = format_time(summary.ReducedSDPTime(i), ...
        summary.ReducedSDPStatus(i));

    fprintf(fid,'%s & %s & %s & %s & %d & %s & %s & %d & %s %s\n', ...
        escape_latex(summary.Instance(i)),optimum,lpBound, ...
        originalBound,summary.OriginalSDPOrder(i),originalTime, ...
        reducedBound,summary.ReducedSDPOrder(i),reducedTime,rowEnd);
end

fprintf(fid,'%s\n','\hline');
fprintf(fid,'%s\n','\end{tabular}');
fprintf(fid,'%s\n','}');
fprintf(fid,'%s\n',['\caption{Comparison of the LP bound, the SDP ', ...
    'relaxation, and the relaxation generated by affine FR}']);
fprintf(fid,'%s\n','\label{tab:sat_results_3}');
fprintf(fid,'%s\n','\end{table}');
end

function text = format_optimum(value,status)
if status == "INFEASIBLE"
    text = 'Inf';
else
    text = format_number(value);
end
end

function text = format_bound(value,status,optimum)
if status == "SKIPPED_OOM_SAFETY" || status == "OOM"
    text = 'OOM';
elseif status == "INFEASIBLE"
    text = '\textbf{Inf}';
elseif isnan(value)
    text = '--';
elseif isfinite(optimum) && abs(value-optimum) < 0.005
    text = ['\textbf{' format_number(value) '}'];
else
    text = format_number(value);
end
end

function text = format_time(value,status)
if status == "SKIPPED_OOM_SAFETY" || status == "OOM" || isnan(value)
    text = '-';
else
    text = sprintf('%.2f',value);
end
end

function text = format_number(value)
if isnan(value)
    text = '--';
elseif isinf(value)
    text = 'Inf';
else
    text = sprintf('%.2f',value);
end
end

function text = escape_latex(value)
text = strrep(char(value),'_','\_');
end
